train:
  seed: 1999
  epochs: 50
  interval: 1
  pretrain: backbones/sp_unet_backbone.pth
  save_epoch: 505

test:
  seed: 1999
  test_topk_per_scene: 100
  test_score_thresh: 0.0
  test_npoint_thresh: 100

dataloader:
  train:
    batch_size: 64
    num_workers: 8
    persistent_workers: True
  val:
    batch_size: 1
    num_workers: 4
    persistent_workers: True
  test:
    batch_size: 1
    num_workers: 2
    persistent_workers: True

data:
  train:
    type: scannetv2_sample_graph_edge
    data_root: data/
    prefix: train
    suffix: .pth
    training: False # not use augmentation
    mode: 4
    with_elastic: False
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
    graph_pos_enc_dim: 5
    max_des_len: 78
  val:
    type: scannetv2_sample_graph_edge
    data_root: data/
    prefix: val
    suffix: .pth
    training: False
    mode: 4
    with_elastic: False
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
    graph_pos_enc_dim: 5
    max_des_len: 78

model:
  input_channel: 6
  blocks: 5
  block_reps: 2
  media: 32
  normalize_before: True
  return_blocks: True
  pool: mean
  sampling_module:
    num_proposal: 512
    pc_dim: 256
    lang_dim: 256
    d_model: 256
  stm: 
    num_layer: 6
    d_model: 256
    nhead: 8
    hidden_dim: 1024
    dropout: 0.0
    activation_fn: gelu
    iter_pred: True
    attn_mask: True
    global_feat: mean
    graph_params:
      num_atom_type: 30523 # tokenizer.vocab_size + 1
      num_bond_type: 40
      hidden_dim: 256
      n_heads: 8
      out_dim: 256
      in_feat_dropout: 0.0
      dropout: 0.0
      n_layers: 12 # 10
      layer_norm: False
      batch_norm: True
      residual: True
      edge_feat: True
      lap_pos_enc: True
      wl_pos_enc: False
      pos_enc_dim: 5 # 10
      full_graph: False
      cat: parallel # parallel
  criterion:
    loss_weight: [1.0, 1.0, 0.5, 5.0]
    loss_fun: focal
  test_cfg:
    topk_insts: 100
    score_thr: 0.0
    npoint_thr: 100
  norm_eval: False
  fix_module: ['bert_encoder',
              'input_conv',
              'unet',
              'output_layer'
              ]

optimizer:
  type: AdamW
  lr: 0.0001
  weight_decay: 0.0005

lr_scheduler:
  type: MultiStepLR
  milestones: [26, 34, 40, 46]
  gamma: 0.5
